-- Fix missing columns in users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS nexus_level INT DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nexus_xp INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS shard_balance INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_elite BOOLEAN DEFAULT FALSE;
